project_id = "ckussqxgvuclnkrgwzaz"

[api]
enabled = true
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://*.vercel.app"]

[storage]
enabled = true
